name: Bug Report（问题反馈）
description: 帮助我们改善此插件
title: "[BUG] "
labels: ["BUG"]
assignees: 
  - MYXXTS
body:
  - type: markdown
    attributes:
      value: |+
        ## PicGo Plugin Chevereto Issue 模板
        ---
        请依照该模板来提交您的问题，否则将会被关闭。
        **反馈前请确认关闭的 Issue 中没有与您遇到的相似的问题，否则同样的提问也会被关闭。**
  - type: checkboxes
    id: read
    attributes:
      label: 前置检查
      description: 我已经查找并检查了如下内容
      options:
        - label: "[README](https://github.com/MYXXTS/Chevereto-Upload#readme)"
          required: true
        - label: "[Issues](https://github.com/MYXXTS/Chevereto-Upload/issues?q=is%3Aissue+is%3Aclosed)"
          required: true
        - label: 插件设置正确无误，且插件为最新版本
          required: true
        - label: Chevereto 网站相关设置无误
          required: true
  - type: dropdown
    id: chevereto_version
    attributes:
      label: 图床版本号
      options:
        - V3
        - V4
    validations:
      required: true
  - type: input
    id: picgo_version
    attributes:
      label: PicGo的版本
      placeholder: 例如 v2.3.0，如果是测试版请说明
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 问题重现
      description: 请复述Bug重现流程
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: 相关日志
      description: 请附上 PicGo 的相关报错日志（用文本的形式）。报错日志可以在 PicGo 设置 -> 设置日志文件 -> 点击打开 后找到
  - type: textarea
    id: screenshot
    attributes:
      label: 相关截图
      description: 如需要截图对问题进行辅助说明，请在此处上传截图
  - type: textarea
    id: other
    attributes:
      label: 补充说明
      description: 如有其他补充说明，请填写在此处
  
